### ISSUE TITLE
late is not correct for _next in chain_of_responsibility

### ISSUE THREAD

**Issue by mortezasojodi** [scottt2/design-patterns-in-dart#10]
when you define _next late, for last Logger we get error (or any logger that we dont need _next ) because this variable is not initilized.
 we must change it to Nullable inctance instead, like below:
Logger? _next;

**Comment by scottt2** [comment]
Hey @mortezasojodi ! Thanks for the report. I should be able to get to fixing this by the weekend or if you want to go ahead and file a PR with the fix. I am always happy to pull in contributor work!
