### ISSUE TITLE
What does ._internal() mean in Singleton Pattern?

### ISSUE THREAD

**Issue by tagirahmad** [scottt2/design-patterns-in-dart#2]
Hello, please, explain, what does ._internal() mean in Singleton Pattern?

```dart

class Me {
  static final Me _singleton = new Me._internal();
  static final String _name = "Tyler";

  factory Me() {
    return _singleton;
  }

  static String get name => _name;
 
  @override
  String toString() => "Hello, my name is $name.";

  Me._internal();
}
```

```dart
Me._internal()
```

**Comment by Foriyo** [comment]
Hii @tagirahmad `_internal()` is a named constructor. Just search about **named constructors in dart** you will get the answer.

**Comment by scottt2** [comment]
@Foriyo Thanks for answering!

@tagirahmad Sorry I completely missed this notification. Please don't ever hesitate to ping my handle directly if you have any future questions.
