### ISSUE TITLE
Improve decorator pattern example

### ISSUE THREAD

**Issue by AliAkberAakash** [scottt2/design-patterns-in-dart#8]
In the decorator pattern example, the two classes are different. The StarbucksDecorator is not decorating an existing coffee object but creating a new coffee object every time. This class should take a coffee object in its constructor and work on it. 
Let me know what you think about it. I'd love to contribute to this.

**Comment by scottt2** [comment]
@AliAkberAakash :heart: it. Definitely cut a PR when you get a chance to fix that. Thanks for identifying this!
